[package]
name = "uberbot"
version = "0.1.0"
edition = "2021"

[dependencies]
irc = "0.15"
tokio = { version = "1", features = ["rt", "macros", "signal"] }
anyhow = "1"
futures = "0"
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
reqwest = "0"
serde_json = "1"
