[package]
name = "uberbot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.15", features = ["rt", "macros", "signal"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = "0.11"
serde_json = "1.0"
fancy-regex = "0.7"
rspotify = "0.11"
htmlescape = "0.3"
toml = "0.5"
serde = "1.0"

[dependencies.async-circe]
path = "async-circe/"
features = ["toml_support"]
