log_level = "debug"  # optional, default: info

[irc]
host = "karx.xyz"
port = 6697
tls = true
username = "uberbot"
nickname = "amazingbot"  # optional, default: same as username
channels = ["#main", "#no-normies"]
mode = "+B"  # optional, default: none
prefix = "u!"

[bot]
db_path = "database.db3"  # optional, default: uberbot.db3
history_depth = 5
search_limit = 5  # optional, default: 3

[spotify]  # optional, spotify module disabled if missing
client_id = ""
client_secret = ""

[web]  # optional, web service disabled if missing
listen = "127.0.0.1:8080"