log_level = "debug"  # optional, default: info

[irc]
host = "karx.xyz"
port = 6697
tls = true
username = "uberbot"
nickname = "amazingbot"  # optional, default: same as username
channels = ["#main", "#no-normies"]
mode = "+B"  # optional, default: none
sasl_pass = "1234"  # optional, does not attempt SASL PLAIN authentication by default 

[bot]
db_path = "database.db3"  # optional, default: uberbot.db3
history_depth = 5
search_limit = 5  # optional, default: 3
prefixes = ["u!", "yo uberbot "]

[spotify]  # optional, spotify module disabled if missing
# you can get those from https://developer.spotify.com/dashboard/
client_id = ""
client_secret = ""

[web]  # optional, web service disabled if missing
listen = "127.0.0.1:8080"

[web.webhooks]  # only required when the web service is enabled
# format: "<path>" = "<irc channel>"
# for example:
"devel" = "#dev"  # http://127.0.0.1:8080/devel
"chaospeople" = "#chaos"  # http://127.0.0.1:8080/chaospeople
