# IRC config
host = "karx.xyz"
port = 6697
username = "uberbot"
channels = ["#main", "#no-normies"]
mode = "+B"

# Spotify config
spotify_client_id = ""
spotify_client_secret = ""

# Bot config
prefix = "!"

# Web service config
http_listen_db = "127.0.0.1:8080"

# Git webhook config
http_listen_git = "127.0.0.1:51001"
git_channel = "#main"

